---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress_server
  #remote_user: root
  remote_user: centos
  become: true

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
